1: /1/*.java
	javac -cp . /1/*.java

2: /2/*.java
	javac -cp . /2/*.java

3/4: /3/4/*.java
	javac -cp . /3/4/*.java

3/5: /3/5/*.java
	javac -cp . /3/5/*.java

3/6: /3/6/*.java
	javac -cp . /3/6/*.java

